### ISSUE TITLE
imagemap组件 按钮样式异常&&事件无效

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#116]
问题类型

bug

功能描述

<img width="684" alt="2017-12-08 11 13 37" src="https://user-images.githubusercontent.com/6095187/33749548-42e348b8-dc09-11e7-81a1-c8c5bd0ff049.png">

**Comment by EarlyH** [comment]
使用的morning版本是多少？

**Comment by EarlyH** [comment]
此问题已经在`0.10.13`版本中修复，请升级版本
