### ISSUE TITLE
getGroup方法无法获取imagemap值

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#118]
**问题类型**

bug

**功能描述**

getGroup方法无法获取imagemap值

<img width="917" alt="2017-12-08 11 54 34" src="https://user-images.githubusercontent.com/6095187/33750428-e528ef10-dc0e-11e7-8e1c-4df69961e903.png">
<img width="330" alt="2017-12-08 11 54 47" src="https://user-images.githubusercontent.com/6095187/33750430-e58558f4-dc0e-11e7-885e-e27fd473ac37.png">

如上图所示，inputtext组件取值正常，而imagemap组件无法取到值

**Comment by EarlyH** [comment]
此问题已经在`0.10.13`中修复，请升级版本
