### ISSUE TITLE
热区及多项表单输入 删除按钮无效

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#124]
**问题类型**

BUG 处理

**问题描述**

组件(目前已知热区及多项表单输入) 删除后 window.morning.getGroup 依旧能取到值。

<img width="856" alt="61a09c14402dc8808b7fe56562d4b0fb" src="https://user-images.githubusercontent.com/6095187/34205329-e573da72-e5bc-11e7-9959-aa42552093c5.png">

**复现步骤**
为组件设置默认值
删除默认值
调用window.morning.getGroup方法 依旧能取到值

**Comment by EarlyH** [comment]
fixed in [0.10.14](https://github.com/Morning-UI/morning-ui/releases/tag/0.10.14)
