### ISSUE TITLE
ui-select组件，clean-btn无效

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#145]
出现不了清空按钮

**Comment by EarlyH** [comment]
try this：
![image](https://user-images.githubusercontent.com/1768041/35661413-f76939e6-074c-11e8-9ba1-73140a1d4efd.png)

cause:

![image](https://user-images.githubusercontent.com/1768041/35661461-4a3c9cee-074d-11e8-9798-e01d68831753.png)
