### ISSUE TITLE
支持检索内容自动重置的配置

### ISSUE THREAD

**Issue by elle0903** [Morning-UI/morning-ui#156]
![image](https://user-images.githubusercontent.com/37177418/38670339-17be1f26-3e7b-11e8-8a95-6516c552b1ae.png)
可搜索可多选的下拉选择框，输入检索内容后找到需要的项目点击后，输入的检索内容没有消失

**Comment by EarlyH** [comment]
这个一个功能，不是bug

**Comment by EarlyH** [comment]
ui-select会增加一个配置，用来决定选中项目后，是否重置检索内容
