### ISSUE TITLE
ui-dropdown会出现下拉菜单被遮挡现象，建议支持设置下拉菜单位置

### ISSUE THREAD

**Issue by elle0903** [Morning-UI/morning-ui#184]
![image](https://user-images.githubusercontent.com/37177418/39743114-82461248-52d2-11e8-9c6d-70729b2d4bc5.png)

建议支持设置位置：下方/上方/左对齐/右对齐

不过最好还是可以进行自适应

**Comment by EarlyH** [comment]
fixed in #186
