### ISSUE TITLE
【datetimepicker】使用is-range和quick-pick的情况下，点击 quick-pick 报错

### ISSUE THREAD

**Issue by elle0903** [Morning-UI/morning-ui#211]
__问题__

【datetimepicker】使用is-range和quick-pick的情况下，点击quick-pick报错

__环境__

- Morning UI版本：0.10.24
- vue：2.52.

__重现步骤__

1、html 如下：

```html
<v-datetimepicker
        :date="+new Date('2018-05-16 11:41:00')"
        :is-range="true"
        :quick-pick="['最近 1 小时', '最近 1 天', '最近 7 天', '最近 30 天', '最近 90 天']"
        :date-selectable-range="['2017-05-17 11:41:00', '2018-05-16 11:41:00']"></v-datetimepicker>
```

2、点击 quick-pick 

![image](https://user-images.githubusercontent.com/37177418/40096455-8c37f37a-5903-11e8-93e4-b99c833584ee.png)

__其他__

原本应当出现在右上角的时间选择不见了。

![image](https://user-images.githubusercontent.com/37177418/40096493-af77c306-5903-11e8-82fa-e54d655f0f42.png)

**Comment by EarlyH** [comment]
请使用版本大于等于`2.5.3`的Vue，更多细节查看：https://github.com/vuejs/vue/releases/tag/v2.5.3

**Comment by EarlyH** [comment]
在Morning后续版本会增加Vue版本检测
