### ISSUE TITLE
组件的get方法应当返回期望的对象或者数组而不是序列化之后的字符串

### ISSUE THREAD

**Issue by ganyouyin** [Morning-UI/morning-ui#22]
### 问题类型

功能请求

### 功能描述

组件的get方法应当返回期望的对象或者数组而不是序列化之后的字符串

### 解决了什么问题

符合使用者预期。

### 期望的时间

ASAP

**Comment by EarlyH** [comment]
这个问题会在0.10.3中更新。

`.get()`方法将返回原始类型数据，`.getJson()`返回JSON序列化字符串
