### ISSUE TITLE
时间选择器支持自动修正

### ISSUE THREAD

**Issue by scaryu** [Morning-UI/morning-ui#302]
在手动直接输入时间的时候，自动修正时间格式

**Comment by EarlyH** [comment]
`ui-timepicker`已经支持自动修正功能：

输入错误的时间：

![image](https://user-images.githubusercontent.com/1768041/40952857-b59dc968-68af-11e8-9407-96958e06dacb.png)


失焦后自动修正：

![image](https://user-images.githubusercontent.com/1768041/40952844-a5ea4d84-68af-11e8-84cd-693cc73375e1.png)
