### ISSUE TITLE
table列宽无法正常设置

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#313]
__问题__

1.为每一个列设置width的情况下，会导致各各col的width设置失效
2.为列设置minwidth或者maxwidth无效

__相关代码__

     colset: [
          {col: 'app', name: 'appId', hide: 'true'},
          {col: 'type', name: '类型', hide: 'true'},
          {col: 'tactics', name: '默认策略', hide: 'true'},
          {col: 'tags', name: '标签', hide: 'true'},
          {col: 'appName', name: '应用', sort: true, title: true, width: '20px'},
          {col: 'key', name: 'KEY', sort: true, title: true, width: '50px'},
          {col: 'desc', name: '描述', sort: true, title: true, width: '50px'},
          {col: 'operate', name: '操作', title : true, width: '50px'},
          {col: 'tagsText', name: '标签'},
          {col: 'tacticsText', name: '默认策略', sort: true},
          {col: 'typeText', name: '类型', sort: true}, 
          {col: 'id', name: 'ID', sort: true}
     ]

或者
    
     colset: [
          {col: 'app', name: 'appId', hide: 'true'},
          {col: 'type', name: '类型', hide: 'true'},
          {col: 'tactics', name: '默认策略', hide: 'true'},
          {col: 'tags', name: '标签', hide: 'true'},
          {col: 'appName', name: '应用', sort: true, title: true, minwidth: '20px'},
          {col: 'key', name: 'KEY', sort: true, title: true, width: '50px'},
          {col: 'desc', name: '描述', sort: true, title: true, width: '50px'},
          {col: 'operate', name: '操作', title : true, width: '50px'},
          {col: 'tagsText', name: '标签'},
          {col: 'tacticsText', name: '默认策略', sort: true},
          {col: 'typeText', name: '类型', sort: true}, 
          {col: 'id', name: 'ID', sort: true}
     ]

填写更多你想阐述的内容。

**Comment by EarlyH** [comment]
> 1.为每一个列设置width的情况下，会导致各各col的width设置失效

`ui-tab`中`col-set`的`width`配置会改变列在宽度分配时的权重，但不一定完全符合设置的宽度值，如果需要控制宽度的绝对值使用minwidth或maxwidth

**Comment by EarlyH** [comment]
> 2.为列设置minwidth或者maxwidth无效

由于标题列的特殊性，请使用`0.11.1`版本中的`title-col-width`配置来实现
