### ISSUE TITLE
select下拉选择组件 数据为空时样式问题

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#319]
__问题__

select下拉选择组件，数据为空时点击下拉没有任何提示

__期望的结果__

下拉组件 数据为空时，提示“空”

**Comment by EarlyH** [comment]
![image](https://user-images.githubusercontent.com/1768041/41820638-9e877370-7807-11e8-867f-db388af3e17f.png)

当数据为空时是有提示的，请提供更多信息以复现你的问题。
