### ISSUE TITLE
select下拉组件 数据量大时没有滚动条

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#320]
__问题__

select下拉组件 数据量大时没有滚动条

__期望的结果__

select下拉组件 数据量大时有滚动条

__问题展示__
git上无法上传图片，图片请访问http://h0.hucdn.com/open/201824/301e13ab3e85febc_457x661.png

**Comment by EarlyH** [comment]
检查一下是否设置了`max-show`配置

**Comment by EarlyH** [comment]
@echoZQ 目前暂时无法复现此问题，请提供更详细的配置
