### ISSUE TITLE
select组件使用multi-select配置 选中后会选择框内会留下输入的文案

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#321]
__问题__

select组件使用multi-select配置 选中后会选择框内会留下输入的文案

__环境__

__重现步骤__

1.键入关键词搜索
2.显示目标下拉选项
3.选中
4.框中有输入的文本

__期望的结果__

选中目标选项后，框中无输入的文本

__图片__

由于github没有办法上传图片，具体情况请访问图片 http://h0.hucdn.com/open/201824/f60e6d5c049152d6_576x442.png

**Comment by EarlyH** [comment]
https://morning-ui.com/component/select.html#auto-reset-search

use `auto-reset-search` config.
