### ISSUE TITLE
table组件的colset能决定数据的列位置

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#388]
__解决了什么__

目前，colset只用来配置，col匹配的数据的属性，比如：name等。支持的属性当中，还希望可以支持col在table的列位置。

__你的解决方案__

可以在colset的配置中，加入 `index` 值，用来决定改列被放置在table的列位置。

__你考虑过的选择__

目前，是严格控制 list 的 key 顺序，来控制 key 的列位置。比较尴尬的是，如果有些key我需要后面才放到obj里面，我要重新排一遍list中 key 顺序，来满足我的需求。

__其他__

目前，列位置是由 `list` 属性决定的。而 list 取值是 [jsonObj, jsonObj]，其子项是 jsonObj，现在位置由 jsonObj 的key顺序来决定。而对象的key本身是可能无序的。

**Comment by EarlyH** [comment]
@CFDylan 

看了下实现现在确实没有考虑list中col的排序问题，目前考虑的方案是，通过`col-set`配置中增加`col-pos`来给予列的排序位置，这是一个数字(大于0的数字)，配置类似：

    :col-set="[{col: 'name', pos: 1}, {col:'age', pos: 2}]"

表格的`list`导入时通过`pos`的大小对列顺序进行排序。
