### ISSUE TITLE
switch组件，当form-name为空或hide-name时，隐藏 .note

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#411]
__解决了什么__

视觉效果，多了空白，不对齐。

__你的解决方案__

加个 `:not(:empty)` 或者直接隐藏
![image](https://user-images.githubusercontent.com/12822730/42799675-492c9d80-89cb-11e8-9faf-845b019dee6b.png)

**Comment by EarlyH** [comment]
使用`hide-name`配置即可隐藏`.note`部分

**Comment by EarlyH** [comment]
![image](https://user-images.githubusercontent.com/1768041/43058579-ee155bd0-8e7a-11e8-87a9-be733edbc16e.png)
