### ISSUE TITLE
custom prefix can't be 'i'

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#54]
When I custom my prefix with 'i', it throws error about max stack.
```js
Vue.use(morning, {
     prefix : 'i'
 });
```

**Comment by EarlyH** [comment]
这是因为morning ui的组件挂载到页面中时，最外层容器是以`i-`作为前缀的。如果使用`i-`作为组件的前缀，就会循环引用组件。我们会在文档中说明这一点。

**Comment by EarlyH** [comment]
考虑`i-`作为比较通用的前缀，组件生成的HTML标签前缀由`i-`变为`mor-`
