### ISSUE TITLE
Need doc for icons

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#60]
* In `ui-select` component, there is a drop icon.
* In `ui-label` component, there is a star icon
```
<ui-label class="icon">
    <i class="iconfont">&#xe6e2;</i>
    <span>标签</span>
</ui-label>
```
So, if i can know which icon is supported and how to use it, it would be amazing!

**Comment by EarlyH** [comment]
文档中使用的icon仅作为示例，在项目中使用时请自行引入icon库。

另外有少量组件内部的icon，已经集成在组件中，无法在组件外部使用。
