### ISSUE TITLE
关于vue嵌套模板上下文

### ISSUE THREAD

**Issue by hileslie** [Morning-UI/morning-ui#649]
提供一个默认上下文this
<ui-table :list="list"></ui-table>
    export default {
        data : {
            list : [
                {name : 'Tim Boelaars', age : 20, gender : 'male', action : '<ui-btn color="success" size="xs" @emit="context.send(0);">第一个发送</ui-btn> <ui-link color="minor" size="xs">详情</ui-link>'}
            ]
        },
        methods : {
            send : function (id) {
                alert(`${this.list[id].name}发送成功!`);
            }
        }
    };

省去context关联this的步骤,这样更接近原生vue模板的使用

**Comment by EarlyH** [comment]
已经在 0.12.28版本中解决
