### ISSUE TITLE
tab 标签页的层次高于侧边栏菜单，导致显示异常

### ISSUE THREAD

**Issue by ganyouyin** [Morning-UI/morning-ui#650]
![image](https://user-images.githubusercontent.com/5118959/56349289-d54fb600-61fa-11e9-870e-92c8270d48b4.png)

**Comment by pwq309** [comment]
和楼主遇到类似的问题：
1. 菜单折叠后，hover 上去二次菜单会被时间选择器挡住：
2. 二级菜单的页面，折叠菜单后刷新页面，二级菜单会默认显示。

![image](https://user-images.githubusercontent.com/13176558/59430314-86965500-8e14-11e9-9670-7ae21b5a628a.png)

**Comment by EarlyH** [comment]
fixed in version 0.12.46
