### ISSUE TITLE
feature: add Toast component

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#67]
When i need to notify users some message, i always choose a Toast component. It may include feature like this:
* type: info, warning, danger
* show from left, top or right
* closed by hand or time out
* show one more Toast at a time which would be queued one by one

Thanks for the author!

**Comment by EarlyH** [comment]
toast常见于移动系统，定义与PC端略有区别，所以采用`ui-message`替代

**Comment by EarlyH** [comment]
> show one more Toast at a time which would be queued one by one

这个暂时不会实现，因为组件之间应该是相互独立的，状态不会互相影响
