### ISSUE TITLE
Bug: Component in table cell can't call root vm function

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#69]
Error in event handler for "emit": "TypeError: showAdDialog is not a function". 

I define `showAdDialog` in the root vm:
```js
new Vue({
    methods: {
         showAdDialog() {}
    }
})
```

**Comment by EarlyH** [comment]
这是因为cell中的component采用动态模板生成，所以无法和父vue实例建立关系。

可以采用全局函数代理：

![image](https://user-images.githubusercontent.com/1768041/33054786-1e0dc2fa-ce41-11e7-89cd-b2160bf02fe1.png)

详见:https://morning-ui.com/component/table.html#内嵌Vue组件
