### ISSUE TITLE
在二级目录子路径命名相同的情况下，导航栏无法正确显示当前菜单

### ISSUE THREAD

**Issue by shelleyIstar** [Morning-UI/morning-ui#700]
__问题__

例如： 当前有两个导航路径， /app/list、/work/list， 当点击/app/list的导航菜单项时，/app/list导航菜单高亮显示同时可以正确打开/app/list下的页面，但是/work/list的导航菜单也会高亮显示。（所有/xx/list的导航菜单都会高亮吸纳是）
当二级路径命名重复的时候，就会出现上述现象。

现象如下图所示：
![image](https://user-images.githubusercontent.com/15376710/60274234-4c57a800-992a-11e9-9bc3-59e941f2fc1e.png)

**Comment by shelleyIstar** [comment]
（所有/xx/list的导航菜单都会高亮吸纳是） =》 （所有/xx/list的导航菜单都会高亮显示）

**Comment by EarlyH** [comment]
fixed in version 0.12.46
