### ISSUE TITLE
ui-menu 暗色系主题，current-menu 颜色不适配

### ISSUE THREAD

**Issue by CFDylan** [Morning-UI/morning-ui#701]
__问题__

配置如下：
```html
<ui-menu
    :menu="menu"
    position="side"
    :position-current="true"
    color="black"
    :side-expand="true"
    :current-menu="currentMenu"
></ui-menu>
```
展示效果：
![image](https://user-images.githubusercontent.com/12822730/60636018-64a65600-9e47-11e9-8806-ff8d1b1df471.png)

__环境__

- Morning UI版本：0.12.45

**Comment by EarlyH** [comment]
fixed in 0.12.48
