### ISSUE TITLE
多选框自带下边距，导致没法上下居中

### ISSUE THREAD

**Issue by pwq309** [Morning-UI/morning-ui#737]
__问题__

多选框自带下边距，导致没法上下居中

__环境__

- Morning UI版本：最新版
- 浏览器：Chrome

__重现步骤__

![image](https://user-images.githubusercontent.com/13176558/66552729-6dac6f00-eb7c-11e9-8eb6-74ceeaadee7c.png)

__期望的结果__

没有下边距

__实际的结果__

有下边距

__其他__

填写更多你想阐述的内容。

**Comment by EarlyH** [comment]
fixed on 0.12.65
