### ISSUE TITLE
morning.findVM('xxx') 无法通过索引指定对象

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#85]
问题类型

功能请求

功能描述

在列表循环中使用ref，使用morning.findVM('xxx')只能定位到数组第一项，不能满足需求

解决了什么问题

现在的方式不符合使用者预期，morning.findVM('xxx') 无法正常使用

**Comment by EarlyH** [comment]
@echoZQ 可以贴一下具体使用的代码吗，包含在template及js

**Comment by echoZQ** [comment]
<li v-for="(item, key, index) in module.modules" v-if="index < 9" :key="item._id">
    <v-link color="danger" ref="cover" v-on:click.native.stop="moduleCover(item._id, index)">
        <i class="iconfont"></i> Cover
    </v-link>
</li>

**Comment by echoZQ** [comment]
`<li v-for="(item, key, index) in module.modules" v-if="index < 9" :key="item._id">
    <v-link color="danger" ref="cover" v-on:click.native.stop="moduleCover(item._id, index)">
        <i class="iconfont"></i> Cover
    </v-link>
</li>

moduleCover(moudleId, index) {
    // todo window.morning.findVM('cover').lock();
    this.vm.$refs.cover[index].lock();
}`

**Comment by echoZQ** [comment]
`<li v-for="(item, key, index) in module.modules" v-if="index < 9" :key="item._id">
    <v-link color="danger" ref="cover" v-on:click.native.stop="moduleCover(item._id, index)"></v-link>
</li>

moduleCover(moudleId, index) {
    // todo window.morning.findVM('cover').lock();
    this.vm.$refs.cover[index].lock();
}`

**Comment by echoZQ** [comment]
<li v-for="(item, key, index) in module.modules" v-if="index < 9" :key="item._id">
    <v-link color="danger" ref="cover" v-on:click.native.stop="moduleCover(item._id, index)"></v-link>
</li>

moduleCover(moudleId, index) {
    // todo window.morning.findVM('cover').lock();
    this.vm.$refs.cover[index].lock();
}

**Comment by echoZQ** [comment]
![image](https://user-images.githubusercontent.com/6095187/33249604-8beb60dc-d366-11e7-9a62-af42fd57616e.png)

**Comment by EarlyH** [comment]
下个版本中会将`findVM`的行为和`$refs`保持一致：https://cn.vuejs.org/v2/guide/components.html#子组件引用

> 当 ref 和 v-for 一起使用时，获取到的引用会是一个数组，包含和循环数据源对应的子组件。
