### ISSUE TITLE
table支持隐藏列

### ISSUE THREAD

**Issue by echoZQ** [Morning-UI/morning-ui#92]
问题类型

功能请求

功能描述

在实现下拉列表搜索的时候，会考虑筛选table中的id而非id转换过的中文内容。同时我又不希望这个用于筛选的id显示在table中，故希望table支持隐藏列

**Comment by EarlyH** [comment]
![image](https://user-images.githubusercontent.com/1768041/33357828-d6c6d286-d4ff-11e7-964f-b5cad7f4eaf2.png)
